### PR TITLE
script.Add accepts a CallableFunc value

### LINKED ISSUE #77: script.Add should accept a CallableFunc value
To be able to directly define a user function
`s.Add("myFunc", myFunc)`

Now, you need to do
`s.Add("myFunc", &objects.UserFunction{Value: myFunc})`

### PR DESCRIPTION
**Pull request by earncef**
fixes #77 

I've the conversion in scripts.Add instead of objects.FromInterface as it is not clear that objects.FromInterface will never be called for builtins.

### CODE REVIEW

**Comment by d5** [comment]
I think it's safe to assume that builtin functions will be defined explicitly, not through `objects.FromInterface`. We can move it inside `objects.FromInterface`.

**Comment by d5** [comment]
Btw, not sure if you know this or not, but, you can auto-close related issue by using 'fixes' or 'resolves': https://help.github.com/en/articles/closing-issues-using-keywords

**Comment by earncef** [comment]
Done

**Comment by d5** [comment]
Thanks @earncef !

**Pull request merged**
