### PR TITLE
bugfix: parse expect error when mis match braces

### PR DESCRIPTION
**Pull request by sailinglawliet**
Change-Id: Iba1ad456d5b020375bb0416f44fb54bc2e346d62

### CODE REVIEW

**Comment by sailinglawliet** [comment]
image

**Comment by sailinglawliet** [comment]
plz review if u guys got time thx @d5  @geseq

**Review by geseq — CHANGES_REQUESTED** [review]
Thanks for the PR. You need to account for the import expression as well

**Comment by sailinglawliet** [comment]
> Thanks for the PR. You need to account for the import expression as well

yeah, i see the check failed, but its due to the wrong test cases, ill fix it as well

**Review by geseq — APPROVED** [review]
Amazing! LGTM

**Comment by sailinglawliet** [comment]
> Amazing! LGTM

Can u tag a new version plz？

**Pull request merged**
