### PR TITLE
Fix parsing oct and hex numbers

### LINKED ISSUE #363: All ints are parsed in base 10
Octal and hexadecimal numbers are partially supported (by scanner), but always parsed in base 10.

#### Expected:

```
fmt := import("fmt")

fmt.println(0123)  // 83
fmt.println(123)   // 123
fmt.println(0x123) // 291
```

#### Actual:

```
fmt := import("fmt")

fmt.println(0123)  // 123
fmt.println(123)   // 123
fmt.println(0x123) // 0
```

### PR DESCRIPTION
**Pull request by qzb**
Fixes #363

### CODE REVIEW

**Review by geseq — APPROVED** [review]
LGTM

**Review by d5 — CHANGES_REQUESTED** [review]
Thanks for the PR. When I tested the following code at the VM-level:

```golang
expectRun(t, `out = 1 + 010`, nil, 9)    // works
expectRun(t, `out = 1 + 0x10`, nil, 17)  // works
expectRun(t, `out = 1 + 0o10`, nil, 9)   // Parse Error: expected ';', found o10
expectRun(t, `out = 1 + 0b10`, nil, 3)   // Parse Error: expected ';', found b10
```

I think we should fix this too if we want to fully support the binary/octal numbers?

**Comment by qzb** [comment]
@d5 I've rewritten numbers scanning from scratch. Instead of trying to scan only valid numbers, it scans for things resembling number and let `strconv` do the validation. It should be fully compatible with golang's int and float literals.

If you don't like those changes, I can revert them and add support only for literals you mentioned.

**Review by geseq — APPROVED** [review]
Nice one!

**Comment by geseq** [comment]
@d5 will need your approval as well

**Review by d5 — APPROVED** [review]

**Pull request merged**
