### PR TITLE
new spread feature

### PR DESCRIPTION
**Pull request by ozanh**
#265 
Docs are still missing but I will add later.
Note: After Ellipsis space is allowed in this implementation not to break compatibility.
Note: Any expression is allowed after ellipsis but it can return an error at parser level but I want to hear your ideas.

### CODE REVIEW

**Comment by d5** [comment]
Didn't look at the code yet, but a couple of questions on the spread operator (`...`):
1. What's the operator precedence?
2. What does spreading map object do? (Do we even need it?)
3. Syntax-wise, how is it different from [ES6](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax)?

**Comment by geseq** [comment]
I don’t think spreading maps is a good idea. It’d make sense to spread map values (or keys) if maps were ordered like they are in some languages, which is not the case in Go and Tengo.

**Comment by ozanh** [comment]
@geseq spread in function calls operates on only array, spread in array operates on only arrays and spread in map operates on only maps. Spread in map does simply merge maps.

**Comment by geseq** [comment]
Ah I see. That sounds a little inconsistent and confusing to me. More so because spreading within maps when a key already exists in the map like below assumes some sort of ordered action within maps:
`{a:1, ...{a:2}, b:2}`

**Comment by ozanh** [comment]
@geseq latter overwrites the former and other languages do the same while merging objects with spread.

**Comment by ozanh** [comment]
@d5 ellipsis has no precedence it is not a binary expression. In the implementation `parseArrayLit parseMapElementLit parseCall` simply checks the token if it is ellipsis and creates `SpreadExpr` which replaces the next expression.

**Comment by geseq** [comment]
I’m not aware of any language that does this with unordered maps. Correct me if I’m wrong, but if you’re referring to JavaScript objects, I believe they do have have an inherent order to the properties even if it’s not insertion based order.

**Comment by ozanh** [comment]
This implementation respects the insertion order and replaces keys if it is defined in spread map. Current implementation of tengo allows this `a := {b:2, b:4}` and `a == {"b":4}` it is not different.

**Comment by ozanh** [comment]
It is just a syntactic sugar to make appending to arrays, merging maps, function calls easier. It is optional though.

**Comment by ozanh** [comment]
>    2. What does spreading map object do? (Do we even need it?)

It merges maps and probably faster than using a for loop.

>     3. Syntax-wise, how is it different from [ES6](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax)?

@d5 it is similar with ES6 spread but function calls do not accept map, only arrays. I am not sure if there are other edge cases, because of that I created a PR as you requested.

**Comment by d5** [comment]
@ozanh I understand this is not final and work in progress. I asked you to open a PR only because it makes it easier to think about and test some edge cases with the real code. It's not to question/debate certain decisions you have made. Just want to clarify that first.

**Comment by ozanh** [comment]
@d5 Thanks for clarification. I started to implement this for just function calls which is highly required by my application. Then I realized that it could be extended to cover spreading arrays and maps without much effort. I am not a fan of spread though. Early implementations were required to have ellipsis after an expression or literal like Go `f(a, b...)` but using ellipsis before improves readability. Just want to give a background why I needed this.
As tengo still does not have an exception handling, it looks like spread is not a priority for now but why not.

**Comment by d5** [comment]
Gotcha. Why don't we start with the function calls first? `f(a, b...)` 

Spreading in the function call is already familiar to Go developers. Also, we can add array/map expansion later if we want to.

**Comment by ozanh** [comment]
Call arguments are expanded under VM `OpCall` so following is valid with current implementation, different than Go.
```go
f := func(a, ...b) {} // a=1, b=[2, 3]
f(...[1, 2, 3])
```
This throws error.
```go
f := func(a, b) {} // accepts 2 arguments, but 3 arguments in stack.
f(...[1, 2, 3])
```
Spread array items are simply appended to VM stack. It is different than Go because of dynamic nature and it is hard to implement one to one argument-parameter match OR I could not figure it out.
If you are OK with loose argument expansion as above I can keep spread in function call and remove spread in array and map.

Note:

Ellipsis (...) position can be before or after expression, it is up to you. But while coding in `parseMapElementLit()` putting ellipsis token before expression created an opportunity to easily check next expression if it is allowed with ellipsis at parser level. Besides, ES6 spread implementation is like that.  No expression type check is implemented currently to discuss it later with you.

**Comment by geseq** [comment]
I think it‘d be better to keep it consistent with go and have ellipses after the expression, unless there’s a significant runtime improvement in changing it.

**Comment by d5** [comment]
Yeah. I think it's better if it's the same (or similar) as Go syntax.

**Comment by ozanh** [comment]
OK it is easy to check ellipsis token after expression is parsed, not a big deal. What I wonder is what to do with `SpreadIn` type constants `SpreadInCall SpreadInArray SpreadInMap`. They are used as operand for `OpSpread` to distinguish where it is used and also passed to custom types implementing Spreader interface which has only method `Spread(parser.SpreadIn) (Object, error)`. Custom objects can be spread like any other array or map with this method. Please have a look at VM tests and play a little bit before proceeding.

**Comment by d5** [comment]
What I'm proposing is to drop array/map spread operator from the implementation for now. Then we wouldn't need `SpreadIn` type/operands, I guess?

**Comment by ozanh** [comment]
Yes we will not need SpreadIn anymore. I am not sure about the OpSpread operand though. Will we need an operand later for something else? When I have time I will create a new PR by closing this just for expand/spread in function calls.

**Pull request closed without merging**
