### PR TITLE
fix documentation for enum.filter

### PR DESCRIPTION
**Pull request by misiek08**
Fixes https://github.com/d5/tengo/issues/358

### CODE REVIEW

**Comment by KEINOS** [comment]
Cool! 👍 

I think we should fix the script comment as well.
https://github.com/d5/tengo/blob/09240a1c1965574c6bfd2a7304a32993d2e2f267/stdlib/srcmod_enum.tengo#L74-L77

**Comment by misiek08** [comment]
Will do this tomorrow, because I need to run/regenerate go file with this source and I need PC to do this :)

**Comment by misiek08** [comment]
Sorry, took much longer because of some unexpected additional work I had to do.

**Review by KEINOS — COMMENTED** [review]
@d5 
This change seems to be OK but doesn't this file be updated via `go generate` by the maintainers?

**Review by KEINOS — APPROVED** [review]
+1 to the changes though.

**Comment by d5** [comment]
I think this PR includes the output of `go generate` as well, right? @misiek08

**Comment by misiek08** [comment]
I ran `go run gensrcmods.go`

**Comment by KEINOS** [comment]
@misiek08

> I ran `go run gensrcmods.go`

Ah, I got it.

That file should be triggered via `go generate ./...` defined in [`stdlib/stdlib.go`'s header](https://github.com/d5/tengo/blob/09240a1c1965574c6bfd2a7304a32993d2e2f267/stdlib/stdlib.go#L3), I think.
They will be overwritten anyway, but the fewer files to review, the better, right?

@d5 

I think it's good to go. What do you think?

**Review by KEINOS — APPROVED** [review]

**Pull request merged**
