### PR TITLE
Revert "remove callable args alloc"

### PR DESCRIPTION
**Pull request by d5**
Reverts d5/tengo#259

### CODE REVIEW

**Comment by d5** [comment]
PR #259 could give `Object.Call` implementations a direct access to vm stack slice, which could lead to unexpected behaviors. I'm sure there exist more obvious examples, but the following code

```golang
package main

import (
	"fmt"

	"github.com/d5/tengo/v2"
)


type MyType struct {
	tengo.ObjectImpl
}

func (o *MyType) TypeName() string {
	return "mytype"
}

func (o *MyType) String() string {
	return ""
}

func (o *MyType) Call(args ...tengo.Object) (tengo.Object, error) {
	return &tengo.Array{Value: args}, nil
}

func (o *MyType) CanCall() bool {
	return true
}

func main() {
	s := tengo.NewScript([]byte(`
a := 1
b := 2
out = {
	res: fn(a, b),
	b: b
}
`))
	_ = s.Add("fn", &MyType{})
	_ = s.Add("out", nil)
	c, err := s.Run()
	if err != nil {
		panic(err)
	}
	fmt.Println(c.Get("out").String())
}
```
should output `{res: [1, 2], b: 2}` but with that PR change it outputs `{res: ["b", 2], b: 2}`.

**Comment by geseq** [comment]
You're right. I also looked into other options such like `copy` but they don't offer any measurable improvement in performance. Better to revert #259

**Comment by ozanh** [comment]
As I see Go uses same slice with spread operator. Sorry about that, I didn't know.

**Comment by d5** [comment]
All good. I really appreciate any efforts to improve performance.

**Pull request merged**
